export type SubseaCable = {
  id: string;
  name: string;
  lengthKm: number;
  landingPoints: string[];
  owners: string;
  readyYear: number;
  description: string;
  coordinates: [number, number][];
};

export const CABLES: SubseaCable[] = [
  {
    id: "marea",
    name: "MAREA (Transatlantic)",
    lengthKm: 6605,
    landingPoints: ["Virginia Beach (USA)", "Bilbao (Spain)"],
    owners: "Telxius, Meta, Microsoft",
    readyYear: 2018,
    description: "Ultra-high-capacity transatlantic subsea cable delivering over 200 Tbps across the Atlantic Ocean.",
    coordinates: [
      [-75.97, 36.85],
      [-65.0, 38.5],
      [-50.0, 41.0],
      [-35.0, 42.5],
      [-20.0, 43.5],
      [-9.0, 43.8],
      [-2.93, 43.26],
    ],
  },
  {
    id: "dunant",
    name: "Dunant (Transatlantic)",
    lengthKm: 6400,
    landingPoints: ["Virginia Beach (USA)", "Saint-Hilaire-de-Riez (France)"],
    owners: "Google",
    readyYear: 2021,
    description: "Google's 12-fiber-pair transatlantic cable featuring space-division multiplexing (SDM) with 250 Tbps capacity.",
    coordinates: [
      [-75.97, 36.85],
      [-62.0, 40.0],
      [-45.0, 44.0],
      [-30.0, 46.5],
      [-15.0, 47.2],
      [-1.94, 46.72],
    ],
  },
  {
    id: "grace-hopper",
    name: "Grace Hopper",
    lengthKm: 6250,
    landingPoints: ["New York (USA)", "Bude (UK)", "Bilbao (Spain)"],
    owners: "Google",
    readyYear: 2022,
    description: "Connects the US East Coast to the United Kingdom and Spain using advanced optical fiber switching.",
    coordinates: [
      [-74.0, 40.7],
      [-60.0, 42.0],
      [-40.0, 46.0],
      [-20.0, 49.0],
      [-4.54, 50.83],
      [-2.93, 43.26],
    ],
  },
  {
    id: "faster",
    name: "FASTER (Transpacific)",
    lengthKm: 11629,
    landingPoints: ["Bandon, Oregon (USA)", "Chiba & Mie (Japan)", "Tamsui (Taiwan)"],
    owners: "Google, China Mobile, KDDI, Singtel",
    readyYear: 2016,
    description: "Transpacific cable system linking the Pacific Northwest of the US to major Japanese & Asian cloud data hubs.",
    coordinates: [
      [-124.4, 43.1],
      [-145.0, 45.0],
      [-170.0, 47.0],
      [175.0, 45.0],
      [155.0, 40.0],
      [140.4, 35.5],
      [136.6, 34.5],
      [121.4, 25.1],
    ],
  },
  {
    id: "seamewe5",
    name: "SEA-ME-WE 5",
    lengthKm: 20000,
    landingPoints: ["Toulon (France)", "Suez (Egypt)", "Mumbai (India)", "Colombo (Sri Lanka)", "Singapore"],
    owners: "Consortium of 19 global telecom operators",
    readyYear: 2017,
    description: "Spans 20,000 km connecting Europe, the Middle East, the Indian subcontinent, and Southeast Asia.",
    coordinates: [
      [5.93, 43.12],
      [15.0, 36.0],
      [28.0, 32.5],
      [32.5, 30.0],
      [38.0, 22.0],
      [45.0, 13.0],
      [58.0, 18.0],
      [72.8, 18.95],
      [79.8, 6.93],
      [95.0, 5.0],
      [103.8, 1.35],
    ],
  },
  {
    id: "2africa",
    name: "2Africa",
    lengthKm: 45000,
    landingPoints: ["United Kingdom", "Portugal", "Ghana", "South Africa", "Kenya", "Egypt", "India"],
    owners: "Meta, Vodafone, Orange, China Mobile, Telecom Egypt",
    readyYear: 2024,
    description: "The longest subsea cable system ever deployed, circling the African continent and linking Europe and Asia.",
    coordinates: [
      [-4.5, 50.8],
      [-9.5, 38.7],
      [-17.0, 20.0],
      [-17.5, 14.7],
      [-0.2, 5.5],
      [8.0, 4.0],
      [18.4, -34.0],
      [32.0, -29.8],
      [40.0, -4.0],
      [45.0, 12.0],
      [34.0, 27.5],
      [32.5, 30.0],
      [72.8, 18.95],
    ],
  },
  {
    id: "southern-cross",
    name: "Southern Cross NEXT",
    lengthKm: 15840,
    landingPoints: ["Sydney (Australia)", "Auckland (New Zealand)", "Suva (Fiji)", "Los Angeles (USA)"],
    owners: "Southern Cross Cables, Telstra, Spark",
    readyYear: 2022,
    description: "High-speed Pacific corridor linking Australasia with the West Coast of the United States.",
    coordinates: [
      [151.2, -33.8],
      [165.0, -34.0],
      [174.7, -36.8],
      [178.4, -18.1],
      [-170.0, -10.0],
      [-150.0, 10.0],
      [-130.0, 25.0],
      [-118.4, 34.0],
    ],
  },
  {
    id: "curie",
    name: "Curie (Pacific South)",
    lengthKm: 10500,
    landingPoints: ["Los Angeles (USA)", "Valparaiso (Chile)", "Panama City (Panama)"],
    owners: "Google",
    readyYear: 2019,
    description: "Direct dedicated optical link between California and Chile, with a branch to Central America.",
    coordinates: [
      [-118.4, 34.0],
      [-110.0, 22.0],
      [-95.0, 10.0],
      [-79.5, 8.9],
      [-80.0, -10.0],
      [-75.0, -25.0],
      [-71.6, -33.0],
    ],
  },
  {
    id: "ellalink",
    name: "EllaLink (South Atlantic)",
    lengthKm: 9300,
    landingPoints: ["Sines (Portugal)", "Fortaleza (Brazil)", "São Paulo (Brazil)"],
    owners: "EllaLink",
    readyYear: 2021,
    description: "First direct high-capacity subsea route connecting Europe and Latin America without passing through North America.",
    coordinates: [
      [-8.87, 37.95],
      [-18.0, 28.0],
      [-25.0, 15.0],
      [-32.0, 0.0],
      [-38.5, -3.7],
      [-46.6, -23.5],
    ],
  },
];

export function cablesCollection(): GeoJSON.FeatureCollection {
  return {
    type: "FeatureCollection",
    features: CABLES.map((c) => ({
      type: "Feature",
      properties: {
        id: c.id,
        name: c.name,
        lengthKm: c.lengthKm,
        landingPoints: c.landingPoints.join(" · "),
        owners: c.owners,
        readyYear: c.readyYear,
      },
      geometry: {
        type: "LineString",
        coordinates: c.coordinates,
      },
    })),
  };
}
